Exception on /login [GET]
Traceback (most recent call last):
  File "/home/schlik/lib/python2.7/Flask-0.10.1-py2.7.egg/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/schlik/lib/python2.7/Flask-0.10.1-py2.7.egg/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/schlik/lib/python2.7/Flask-0.10.1-py2.7.egg/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/schlik/lib/python2.7/Flask-0.10.1-py2.7.egg/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/schlik/lib/python2.7/Flask-0.10.1-py2.7.egg/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/schlik/webapps/stockmarketsavant/htdocs/index.py", line 48, in showLogin
    login_session['state'] = state
  File "/home/schlik/lib/python2.7/Werkzeug-0.10.4-py2.7.egg/werkzeug/local.py", line 341, in __setitem__
    self._get_current_object()[key] = value
  File "/home/schlik/lib/python2.7/Flask-0.10.1-py2.7.egg/flask/sessions.py", line 126, in _fail
    raise RuntimeError('the session is unavailable because no secret '
RuntimeError: the session is unavailable because no secret key was set.  Set the secret_key on the application to something unique and secret.
Exception on /gconnect [POST]
Traceback (most recent call last):
  File "/home/schlik/lib/python2.7/Flask-0.10.1-py2.7.egg/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/schlik/lib/python2.7/Flask-0.10.1-py2.7.egg/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/schlik/lib/python2.7/Flask-0.10.1-py2.7.egg/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/schlik/lib/python2.7/Flask-0.10.1-py2.7.egg/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/schlik/lib/python2.7/Flask-0.10.1-py2.7.egg/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/schlik/webapps/stockmarketsavant/htdocs/index.py", line 84, in gconnect
    oauth_flow = flow_from_clientsecrets('client_secrets.json', scope='' )
  File "/home/schlik/lib/python2.7/oauth2client-1.4.7-py2.7.egg/oauth2client/util.py", line 137, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/schlik/lib/python2.7/oauth2client-1.4.7-py2.7.egg/oauth2client/client.py", line 2007, in flow_from_clientsecrets
    client_type, client_info = clientsecrets.loadfile(filename, cache=cache)
  File "/home/schlik/lib/python2.7/oauth2client-1.4.7-py2.7.egg/oauth2client/clientsecrets.py", line 155, in loadfile
    return _loadfile(filename)
  File "/home/schlik/lib/python2.7/oauth2client-1.4.7-py2.7.egg/oauth2client/clientsecrets.py", line 115, in _loadfile
    raise InvalidClientSecretsError('File not found: "%s"' % filename)
InvalidClientSecretsError: File not found: "client_secrets.json"
Exception on /gconnect [POST]
Traceback (most recent call last):
  File "/home/schlik/lib/python2.7/Flask-0.10.1-py2.7.egg/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/schlik/lib/python2.7/Flask-0.10.1-py2.7.egg/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/schlik/lib/python2.7/Flask-0.10.1-py2.7.egg/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/schlik/lib/python2.7/Flask-0.10.1-py2.7.egg/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/schlik/lib/python2.7/Flask-0.10.1-py2.7.egg/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/schlik/webapps/stockmarketsavant/htdocs/index.py", line 84, in gconnect
    oauth_flow = flow_from_clientsecrets('client_secrets.json', scope='' )
  File "/home/schlik/lib/python2.7/oauth2client-1.4.7-py2.7.egg/oauth2client/util.py", line 137, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/schlik/lib/python2.7/oauth2client-1.4.7-py2.7.egg/oauth2client/client.py", line 2007, in flow_from_clientsecrets
    client_type, client_info = clientsecrets.loadfile(filename, cache=cache)
  File "/home/schlik/lib/python2.7/oauth2client-1.4.7-py2.7.egg/oauth2client/clientsecrets.py", line 155, in loadfile
    return _loadfile(filename)
  File "/home/schlik/lib/python2.7/oauth2client-1.4.7-py2.7.egg/oauth2client/clientsecrets.py", line 115, in _loadfile
    raise InvalidClientSecretsError('File not found: "%s"' % filename)
InvalidClientSecretsError: File not found: "client_secrets.json"
In showLogin()
state is S7QTDRPHII9IF3E2VPG1IRBUJQDWES0M
login_session[state] is S7QTDRPHII9IF3E2VPG1IRBUJQDWES0M
In showLogin()
state is VTIZWV0LLMWANMMNQ6AKLUGXNV2SR8CY
login_session[state] is VTIZWV0LLMWANMMNQ6AKLUGXNV2SR8CY
login_session[state] is 6SML9VXCLGBCQMWY8THRZ1DDADODUH9C
login_session[state] is 3LVR9AANOWKS562WGII0GDZ37OK9RTCR
login_session[state] is BB4NJGRQ086AN8HNOYNYQHZQ3103Z0WM
login_session[state] is LENZV5V8Y8IXERL4I2VLQ5QTISPL2K9V
Exception on /gconnect [POST]
Traceback (most recent call last):
  File "/home/schlik/lib/python2.7/Flask-0.10.1-py2.7.egg/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/schlik/lib/python2.7/Flask-0.10.1-py2.7.egg/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/schlik/lib/python2.7/Flask-0.10.1-py2.7.egg/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/schlik/lib/python2.7/Flask-0.10.1-py2.7.egg/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/schlik/lib/python2.7/Flask-0.10.1-py2.7.egg/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/schlik/webapps/stockmarketsavant/htdocs/index.py", line 82, in gconnect
    oauth_flow = flow_from_clientsecrets('client_secrets.json', scope='' )
  File "/home/schlik/lib/python2.7/oauth2client-1.4.7-py2.7.egg/oauth2client/util.py", line 137, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/schlik/lib/python2.7/oauth2client-1.4.7-py2.7.egg/oauth2client/client.py", line 2007, in flow_from_clientsecrets
    client_type, client_info = clientsecrets.loadfile(filename, cache=cache)
  File "/home/schlik/lib/python2.7/oauth2client-1.4.7-py2.7.egg/oauth2client/clientsecrets.py", line 155, in loadfile
    return _loadfile(filename)
  File "/home/schlik/lib/python2.7/oauth2client-1.4.7-py2.7.egg/oauth2client/clientsecrets.py", line 115, in _loadfile
    raise InvalidClientSecretsError('File not found: "%s"' % filename)
InvalidClientSecretsError: File not found: "client_secrets.json"
login_session[state] is 484Z5IRIXI52DU5QJF9ZUVXH9CN0IRTC
login_session[state] is ZGCZK29GN1LPKSIV02INGLM6YMX7V9IX
login_session[state] is BP8E2RL1A9V93FGE8Y4KO1FG740KM4MS
login_session[state] is D9VUW0635G2CWUQAJHJLXQT8QJPU9P6B
login_session[state] is P5WBF99W4TAOIQC9GIHACGE5884Y5H4C
login_session[state] is QEW2N8UF50469IGF3DUJVYTGATX0R7GC
login_session[state] is MNKNL4ZB8V2MKY4X5TPQAQKKBMGDGOOE
login_session[state] is H6KCN2BI5YWDZ6O4C1G5WXVIY5BPZVJ0
login_session[state] is QGDSZD28505KU9KAPN45ZTE41H133F28
login_session[state] is 5DKVV6QS32S7ZOJT06MSBBT7K9M3P19C
login_session[state] is DYSTJISKALLSVRLIQPU3FVQB105WHI1Q
login_session[state] is QTVWY0DR7VVE099OHT242N2BWJD8IZYB
login_session[state] is NYU1RU00VTOWK72WNOGNACZX994EE77N
setupAccount() : name is WolfOfWallStreet
Exception on /gconnect [POST]
Traceback (most recent call last):
  File "/home/schlik/lib/python2.7/Flask-0.10.1-py2.7.egg/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/schlik/lib/python2.7/Flask-0.10.1-py2.7.egg/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/schlik/lib/python2.7/Flask-0.10.1-py2.7.egg/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/schlik/lib/python2.7/Flask-0.10.1-py2.7.egg/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/schlik/lib/python2.7/Flask-0.10.1-py2.7.egg/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/schlik/webapps/stockmarketsavant/htdocs/index.py", line 82, in gconnect
    oauth_flow = flow_from_clientsecrets('client_secrets.json', scope='' )
  File "/home/schlik/lib/python2.7/oauth2client-1.4.7-py2.7.egg/oauth2client/util.py", line 137, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/schlik/lib/python2.7/oauth2client-1.4.7-py2.7.egg/oauth2client/client.py", line 2007, in flow_from_clientsecrets
    client_type, client_info = clientsecrets.loadfile(filename, cache=cache)
  File "/home/schlik/lib/python2.7/oauth2client-1.4.7-py2.7.egg/oauth2client/clientsecrets.py", line 155, in loadfile
    return _loadfile(filename)
  File "/home/schlik/lib/python2.7/oauth2client-1.4.7-py2.7.egg/oauth2client/clientsecrets.py", line 115, in _loadfile
    raise InvalidClientSecretsError('File not found: "%s"' % filename)
InvalidClientSecretsError: File not found: "client_secrets.json"
Exception on /gconnect [POST]
Traceback (most recent call last):
  File "/home/schlik/lib/python2.7/Flask-0.10.1-py2.7.egg/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/schlik/lib/python2.7/Flask-0.10.1-py2.7.egg/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/schlik/lib/python2.7/Flask-0.10.1-py2.7.egg/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/schlik/lib/python2.7/Flask-0.10.1-py2.7.egg/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/schlik/lib/python2.7/Flask-0.10.1-py2.7.egg/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/schlik/webapps/stockmarketsavant/htdocs/index.py", line 82, in gconnect
    oauth_flow = flow_from_clientsecrets('client_secrets.json', scope='' )
  File "/home/schlik/lib/python2.7/oauth2client-1.4.7-py2.7.egg/oauth2client/util.py", line 137, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/schlik/lib/python2.7/oauth2client-1.4.7-py2.7.egg/oauth2client/client.py", line 2007, in flow_from_clientsecrets
    client_type, client_info = clientsecrets.loadfile(filename, cache=cache)
  File "/home/schlik/lib/python2.7/oauth2client-1.4.7-py2.7.egg/oauth2client/clientsecrets.py", line 155, in loadfile
    return _loadfile(filename)
  File "/home/schlik/lib/python2.7/oauth2client-1.4.7-py2.7.egg/oauth2client/clientsecrets.py", line 115, in _loadfile
    raise InvalidClientSecretsError('File not found: "%s"' % filename)
InvalidClientSecretsError: File not found: "client_secrets.json"
login_session[state] is OSVWBWSGCL98TBN6BKQDWLSRUUAEREEJ
Exception on /gconnect [POST]
Traceback (most recent call last):
  File "/home/schlik/lib/python2.7/Flask-0.10.1-py2.7.egg/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/schlik/lib/python2.7/Flask-0.10.1-py2.7.egg/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/schlik/lib/python2.7/Flask-0.10.1-py2.7.egg/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/schlik/lib/python2.7/Flask-0.10.1-py2.7.egg/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/schlik/lib/python2.7/Flask-0.10.1-py2.7.egg/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/schlik/webapps/stockmarketsavant/htdocs/index.py", line 82, in gconnect
    oauth_flow = flow_from_clientsecrets('client_secrets.json', scope='' )
  File "/home/schlik/lib/python2.7/oauth2client-1.4.7-py2.7.egg/oauth2client/util.py", line 137, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/schlik/lib/python2.7/oauth2client-1.4.7-py2.7.egg/oauth2client/client.py", line 2007, in flow_from_clientsecrets
    client_type, client_info = clientsecrets.loadfile(filename, cache=cache)
  File "/home/schlik/lib/python2.7/oauth2client-1.4.7-py2.7.egg/oauth2client/clientsecrets.py", line 155, in loadfile
    return _loadfile(filename)
  File "/home/schlik/lib/python2.7/oauth2client-1.4.7-py2.7.egg/oauth2client/clientsecrets.py", line 115, in _loadfile
    raise InvalidClientSecretsError('File not found: "%s"' % filename)
InvalidClientSecretsError: File not found: "client_secrets.json"
